const ADD_CONTACT = 'ADD_CONTACT';

const DELETE_CONTACT = 'DELETE_CONTACT';

const UPDATE_CHATITEM = 'UPDATE_CHATITEM';

const ADD_CHATITEM = 'ADD_CHATITEM';

const CHANGE_CURRENT_CHATEITEM_INDEX = 'CHANGE_CURRENT_CHATEITEM_INDEX';

const DELETE_CHATITEM = 'DELETE_CHATITEM';

const SEND_MESSAGE = 'SEND_MESSAGE';

const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export default {
  ADD_CONTACT,
  DELETE_CONTACT,
  UPDATE_CHATITEM,
  ADD_CHATITEM,
  CHANGE_CURRENT_CHATEITEM_INDEX,
  DELETE_CHATITEM,
  SEND_MESSAGE,
  RECEIVE_MESSAGE
};
